//Nombre
export const GET_NOMBRE = "GET_NOMBRE ";
export const GET_NOMBRE_SUCCESS = "GET_NOMBRE_SUCCESS ";
export const GET_NOMBRE_FAILED = "GET_NOMBRE_FAILED ";

//Productos
export const GET_PRODUCTOS = "GET_PRODUCTOS ";
export const GET_PRODUCTOS_SUCCESS = "GET_PRODUCTOS_SUCCESS ";
export const GET_PRODUCTOS_FAILED = "GET_PRODUCTOS_FAILED ";

export const PUT_PRODUCTO = "PUT_PRODUCTO ";
export const PUT_PRODUCTO_SUCCESS = "PUT_PRODUCTO_SUCCESS ";
export const PUT_PRODUCTO_FAILED = "PUT_PRODUCTO_FAILED ";

export const POST_PRODUCTO = "POST_PRODUCTO ";
export const POST_PRODUCTO_SUCCESS = "POST_PRODUCTO_SUCCESS ";
export const POST_PRODUCTO_FAILED = "POST_PRODUCTO_FAILED ";

export const DELETE_PRODUCTO = "DELETE_PRODUCTO ";
export const DELETE_PRODUCTO_SUCCESS = "DELETE_PRODUCTO_SUCCESS ";
export const DELETE_PRODUCTO_FAILED = "DELETE_PRODUCTO_FAILED ";

//Productos Vendidos
export const GET_PRODUCTOSVENDIDOS = "GET_PRODUCTOSVENDIDOS ";
export const GET_PRODUCTOSVENDIDOS_SUCCESS = "GET_PRODUCTOSVENDIDOS_SUCCESS ";
export const GET_PRODUCTOSVENDIDOS_FAILED = "GET_PRODUCTOSVENDIDOS_FAILED ";

//Usuario
export const POST_USUARIO = "POST_USUARIO ";
export const POST_USUARIO_SUCCESS = "POST_USUARIO_SUCCESS ";
export const POST_USUARIO_FAILED = "POST_USUARIO_FAILED ";

export const GET_USUARIOBYNOMBRE = "GET_USUARIOBYNOMBRE ";
export const GET_USUARIOBYNOMBRE_SUCCESS = "GET_USUARIOBYNOMBRE_SUCCESS ";
export const GET_USUARIOBYNOMBRE_FAILED = "GET_USUARIOBYNOMBRE_FAILED ";


export const GET_USUARIO = "GET_USUARIO ";
export const GET_USUARIO_SUCCESS = "GET_USUARIO_SUCCESS ";
export const GET_USUARIO_FAILED = "GET_USUARIO_FAILED ";

export const PUT_USUARIO = "PUT_USUARIO ";
export const PUT_USUARIO_SUCCESS = "PUT_USUARIO_SUCCESS ";
export const PUT_USUARIO_FAILED = "PUT_USUARIO_FAILED ";


//Ventas
export const GET_VENTAS = "GET_VENTAS ";
export const GET_VENTAS_SUCCESS = "GET_VENTAS_SUCCESS ";
export const GET_VENTAS_FAILED = "GET_VENTAS_FAILED ";

export const POST_VENTAS = "POST_VENTAS ";
export const POST_VENTAS_SUCCESS = "POST_VENTAS_SUCCESS ";
export const POST_VENTAS_FAILED = "POST_VENTAS_FAILED ";